version: "3.5"
services:
  db:
    image: postgres:13.7
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - 55432:5432
  apiserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: apiserver:latest
    depends_on:
      - db
    environment:
      - POSTGRES_URL=postgresql://postgres:12345@db:5432/postgres
    ports:
      - 8000:80